export default {
    myAccountBtn: 'span.d-none',
    toLoginBtn: 'a.dropdown-item',
    toRegisterBtn: 'a.dropdown-item',
    emailInput: '[id="input-email"]',
    passwordInput: '[id="input-password"]',
    firstNameInput: '[id="input-firstname"]',
    lastNameInput: '[id="input-lastname"]',
    loginBtn: 'button.btn-primary',
    validationLoginMsg: '[id="alert"]',
    validationRegisterMsg: 'div.invalid-feedback',
    forgottenPassBtn: 'a',
    continueBtn: 'button.btn-primary',
    alertSucces: 'div.alert-success',
    breadcrumbItem: 'li.breadcrumb-item',
    privacyPolicyToggle: '[name="agree"]',
    successMsg: '[id="content"]',
};